trigger:
  branches:
   include:
     - main
pool:
 name: clone
stages:
  - stage: Build
    jobs:
      - job: npmbuild
        steps:
          - task: Npm@1
            inputs:
              command: 'install'

          - task: Docker@2
            inputs:
              containerRegistry: 'Docker connection'
              repository: 'vaidehisatpute/clonedocker'
              command: 'buildAndPush'
              Dockerfile: 'Dockerfile'
              



 
     
