trigger:
 branches:
   include:
     - main
   exclude: []

pool: 
 name: clone


stages:
- stage: Build
  jobs:
  - job: Build
    displayName: installing package
    steps:
    - script: sudo apt install nodejs npm
      displayName: installing node js
    - script: nmp install
      displayName: installing npm packages angular application 
            
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'build'
        ArtifactName: 'drop'
        publishLocation: 'Container'
    


 



 
     
